module.exports.descriptors = [
    'Legendary',
    'Champion',
    'Historic',
    'Rising',
    'Fierce',
    'Underdog',
    'Brilliant',
    'Tactical',
    'Golden',
    'Defensive',
    'Attacking',
    'Skillful',
    'Fast',
    'Fearless',
    'Aggressive',
    'Strategic',
    'Dynamic',
    'United',
    'Victorious'
]

module.exports.places = [
    'Arena',
    'Stadium',
    'Park',
    'Ground',
    'Field',
    'Pitch',
    'Dome',
    'Coliseum',
    'Complex',
    'Academy',
    'Training Ground',
    'Headquarters',
    'Camp',
    'Base',
    'Clubhouse',
    'Arena',
    'Court',
    'Side',
    'Territory',
    'Home Ground'
]
